### PR TITLE
added 4BXI end fed antenna article.

### PR DESCRIPTION
**Pull request by BelFess**
Added 4BXI end fed antenna article. I followed the current structure of a folder per project.
Also accidentally moved the flowerpot PDF and restored in the original folder - please check that.

### CODE REVIEW

**Review by AshleyRoll — COMMENTED** [review]
I am not sure why I'm seeing a change to the flowerpot antenna pdf? Any ideas?

**Comment by BelFess** [comment]
Because I've accidentally moved it into the End Fed folder and then moved it back into the flowerpot antenna. 
It got marked as a change

**Comment by BelFess** [comment]
can you reject just that part of the change?

**Comment by AshleyRoll** [comment]
No its not possible.. Let me fix the commit..

**Comment by BelFess** [comment]
I'm happy to delete and so it again

**Review by AshleyRoll — APPROVED** [review]
I fixed the commit and force pushed it. Good to go.

**Pull request merged**
